version: 1
builder:
  configs:
    - documentation_targets:
        - CommandPaletteKit
      test_targets:
        - CommandPaletteKitTests
      platform_versions:
        - name: tvOS
          version: '17.0'
